# Gebruik een officiële PHP beeld als basis
FROM php:8.1-apache

# Installeer systeemafhankelijkheden
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl

# Installeer PHP-extensies
RUN docker-php-ext-install pdo pdo_mysql gd

# Installeer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Stel de werkmap in
WORKDIR /var/www

# Kopieer het huidige project naar de werkmap
COPY . /var/www

# Installeer project afhankelijkheden
RUN composer install

RUN composer update


# Stel de rechten in voor de Laravel storage map
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Stel de startopdracht in
CMD ["apache2-foreground"]
